/**
 * Tailwind preset de @sincpro/mobile-ui.
 * Trae todos los tokens por defecto (colores como CSS variables, tipografía,
 * spacing, radios, sombras) listos para usar.
 *
 * Uso en la app consumidora (tailwind.config.js):
 *   module.exports = {
 *     presets: [require("@sincpro/mobile-ui/tailwind.preset")],
 *     content: [
 *       "./App.{js,jsx,ts,tsx}",
 *       "./src/**\/*.{js,jsx,ts,tsx}",
 *       "./node_modules/@sincpro/mobile/**\/*.js",
 *       "./node_modules/@sincpro/mobile-ui/**\/*.js",
 *     ],
 *     theme: { extend: { colors: { brand: "#FF6600" } } }, // tus tokens custom
 *   };
 *
 * Para cambiar los valores del tema: sobreescribe las CSS variables en tu
 * global.css (:root { --primary: 255 102 0; ... }) o en runtime con vars().
 */
module.exports = {
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "rgb(var(--primary) / <alpha-value>)",
        secondary: "rgb(var(--secondary) / <alpha-value>)",
        accent: "rgb(var(--accent) / <alpha-value>)",
        bg: {
          page: "rgb(var(--bg-page) / <alpha-value>)",
          card: "rgb(var(--bg-card) / <alpha-value>)",
          popover: "rgb(var(--bg-popover) / <alpha-value>)",
          muted: "rgb(var(--bg-muted) / <alpha-value>)",
          accent: "rgb(var(--bg-accent) / <alpha-value>)",
          hover: "rgb(var(--bg-hover) / <alpha-value>)",
          disabled: "rgb(var(--bg-disabled) / <alpha-value>)",
        },
        text: {
          primary: "rgb(var(--text-primary) / <alpha-value>)",
          secondary: "rgb(var(--text-secondary) / <alpha-value>)",
          tertiary: "rgb(var(--text-tertiary) / <alpha-value>)",
          muted: "rgb(var(--text-muted) / <alpha-value>)",
          accent: "rgb(var(--text-accent) / <alpha-value>)",
          inverse: "rgb(var(--text-inverse) / <alpha-value>)",
          disabled: "rgb(var(--text-disabled) / <alpha-value>)",
          "on-primary": "rgb(var(--text-on-primary) / <alpha-value>)",
          "on-secondary": "rgb(var(--text-on-secondary) / <alpha-value>)",
          "on-accent": "rgb(var(--text-on-accent) / <alpha-value>)",
          "on-danger": "rgb(var(--text-on-danger) / <alpha-value>)",
          "on-success": "rgb(var(--text-on-success) / <alpha-value>)",
        },
        icon: {
          primary: "rgb(var(--icon-primary) / <alpha-value>)",
          secondary: "rgb(var(--icon-secondary) / <alpha-value>)",
          tertiary: "rgb(var(--icon-tertiary) / <alpha-value>)",
          inverse: "rgb(var(--icon-inverse) / <alpha-value>)",
          disabled: "rgb(var(--icon-disabled) / <alpha-value>)",
        },
        border: {
          default: "rgb(var(--border-default) / <alpha-value>)",
          light: "rgb(var(--border-light) / <alpha-value>)",
          strong: "rgb(var(--border-strong) / <alpha-value>)",
          focus: "rgb(var(--border-focus) / <alpha-value>)",
        },
        success: "rgb(var(--success) / <alpha-value>)",
        warning: "rgb(var(--warning) / <alpha-value>)",
        danger: "rgb(var(--danger) / <alpha-value>)",
        info: "rgb(var(--info) / <alpha-value>)",
        "success-light": "rgb(var(--success-light) / <alpha-value>)",
        "warning-light": "rgb(var(--warning-light) / <alpha-value>)",
        "danger-light": "rgb(var(--danger-light) / <alpha-value>)",
        "info-light": "rgb(var(--info-light) / <alpha-value>)",
        ring: "rgb(var(--ring) / <alpha-value>)",
        input: "rgb(var(--input) / <alpha-value>)",
      },
      fontFamily: {
        light: ["Montserrat_300Light"],
        regular: ["Montserrat_400Regular"],
        medium: ["Montserrat_500Medium"],
        semibold: ["Montserrat_600SemiBold"],
        extrabold: ["Montserrat_800ExtraBold"],
      },
      fontSize: {
        xs: ["10px", { lineHeight: "16px" }],
        sm: ["13px", { lineHeight: "18px" }],
        base: ["14px", { lineHeight: "20px" }],
        lg: ["16px", { lineHeight: "24px" }],
        xl: ["18px", { lineHeight: "28px" }],
        "2xl": ["20px", { lineHeight: "28px" }],
        "3xl": ["24px", { lineHeight: "32px" }],
        "4xl": ["28px", { lineHeight: "36px" }],
        "5xl": ["32px", { lineHeight: "40px" }],
        "6xl": ["36px", { lineHeight: "44px" }],
        "7xl": ["48px", { lineHeight: "56px" }],
        "8xl": ["64px", { lineHeight: "72px" }],
      },
      spacing: {
        0: "0px",
        0.5: "2px",
        1: "4px",
        1.5: "6px",
        2: "8px",
        2.5: "10px",
        3: "12px",
        3.5: "14px",
        4: "16px",
        5: "20px",
        6: "24px",
        7: "28px",
        8: "32px",
        9: "36px",
        10: "40px",
        11: "44px",
        12: "48px",
        14: "56px",
        15: "60px",
        16: "64px",
        20: "80px",
        24: "96px",
        28: "112px",
        32: "128px",
      },
      borderRadius: {
        none: "0px",
        sm: "4px",
        DEFAULT: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "24px",
        "3xl": "32px",
        full: "9999px",
      },
      boxShadow: {
        sm: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
        DEFAULT: "0 2px 4px 0 rgba(0, 0, 0, 0.1)",
        md: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
        lg: "0 10px 15px -3px rgba(0, 0, 0, 0.1)",
        xl: "0 20px 25px -5px rgba(0, 0, 0, 0.1)",
        "2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
        none: "none",
      },
    },
  },
  plugins: [],
};
