import type { ThemeTokens } from "./types";

export const DEFAULT_THEME: ThemeTokens = {
  name: "default",
  primary: "#2563EB",
  secondary: "#64748B",
  accent: "#F59E0B",
  bg: {
    page: "#F9FAFB",
    card: "#FFFFFF",
    popover: "#FFFFFF",
    muted: "#F3F4F6",
    accent: "#EFF6FF",
    hover: "#F3F4F6",
    disabled: "#F3F4F6",
  },
  text: {
    primary: "#0F172A",
    secondary: "#475569",
    tertiary: "#94A3B8",
    muted: "#64748B",
    accent: "#1E40AF",
    inverse: "#FFFFFF",
    disabled: "#94A3B8",
    onPrimary: "#FFFFFF",
    onSecondary: "#FFFFFF",
    onAccent: "#FFFFFF",
    onDanger: "#FFFFFF",
    onSuccess: "#FFFFFF",
  },
  icon: {
    primary: "#0F172A",
    secondary: "#64748B",
    tertiary: "#94A3B8",
    inverse: "#FFFFFF",
    disabled: "#CBD5E1",
  },
  border: {
    default: "#E5E7EB",
    light: "#F3F4F6",
    strong: "#D1D5DB",
    focus: "#2563EB",
  },
  success: "#16A34A",
  warning: "#F59E0B",
  danger: "#DC2626",
  info: "#2563EB",
  successLight: "#DCFCE7",
  warningLight: "#FEF3C7",
  dangerLight: "#FEE2E2",
  infoLight: "#DBEAFE",
  ring: "#2563EB",
  input: "#E5E7EB",
  gradient: {
    primary: ["#2563EB", "#1E40AF"],
    accent: ["#F59E0B", "#D97706"],
  },
  shadow: {
    sm: {
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 6,
      elevation: 3,
    },
    lg: {
      shadowColor: "#000000",
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.1,
      shadowRadius: 15,
      elevation: 5,
    },
  },
};
